export const STATES = [
  { value: 'AR', label: 'Arkansas', region: 'South' },
  { value: 'OK', label: 'Oklahoma', region: 'South' },
  { value: 'AL', label: 'Alabama', region: 'South' },
  { value: 'AK', label: 'Alaska', region: 'West' },
  { value: 'AZ', label: 'Arizona', region: 'West' },
  { value: 'CA', label: 'California', region: 'West' },
  { value: 'CO', label: 'Colorado', region: 'West' },
  { value: 'CT', label: 'Connecticut', region: 'Northeast' },
  { value: 'DE', label: 'Delaware', region: 'Northeast' },
  { value: 'FL', label: 'Florida', region: 'South' },
  { value: 'GA', label: 'Georgia', region: 'South' },
  { value: 'HI', label: 'Hawaii', region: 'West' },
  { value: 'ID', label: 'Idaho', region: 'West' },
  { value: 'IL', label: 'Illinois', region: 'Midwest' },
  { value: 'IN', label: 'Indiana', region: 'Midwest' },
  { value: 'IA', label: 'Iowa', region: 'Midwest' },
  { value: 'KS', label: 'Kansas', region: 'Midwest' },
  { value: 'KY', label: 'Kentucky', region: 'South' },
  { value: 'LA', label: 'Louisiana', region: 'South' },
  { value: 'ME', label: 'Maine', region: 'Northeast' },
  { value: 'MD', label: 'Maryland', region: 'Northeast' },
  { value: 'MA', label: 'Massachusetts', region: 'Northeast' },
  { value: 'MI', label: 'Michigan', region: 'Midwest' },
  { value: 'MN', label: 'Minnesota', region: 'Midwest' },
  { value: 'MS', label: 'Mississippi', region: 'South' },
  { value: 'MO', label: 'Missouri', region: 'Midwest' },
  { value: 'MT', label: 'Montana', region: 'West' },
  { value: 'NE', label: 'Nebraska', region: 'Midwest' },
  { value: 'NV', label: 'Nevada', region: 'West' },
  { value: 'NH', label: 'New Hampshire', region: 'Northeast' },
  { value: 'NJ', label: 'New Jersey', region: 'Northeast' },
  { value: 'NM', label: 'New Mexico', region: 'West' },
  { value: 'NY', label: 'New York', region: 'Northeast' },
  { value: 'NC', label: 'North Carolina', region: 'South' },
  { value: 'ND', label: 'North Dakota', region: 'Midwest' },
  { value: 'OH', label: 'Ohio', region: 'Midwest' },
  { value: 'OR', label: 'Oregon', region: 'West' },
  { value: 'PA', label: 'Pennsylvania', region: 'Northeast' },
  { value: 'RI', label: 'Rhode Island', region: 'Northeast' },
  { value: 'SC', label: 'South Carolina', region: 'South' },
  { value: 'SD', label: 'South Dakota', region: 'Midwest' },
  { value: 'TN', label: 'Tennessee', region: 'South' },
  { value: 'TX', label: 'Texas', region: 'South' },
  { value: 'UT', label: 'Utah', region: 'West' },
  { value: 'VT', label: 'Vermont', region: 'Northeast' },
  { value: 'VA', label: 'Virginia', region: 'South' },
  { value: 'WA', label: 'Washington', region: 'West' },
  { value: 'WV', label: 'West Virginia', region: 'South' },
  { value: 'WI', label: 'Wisconsin', region: 'Midwest' },
  { value: 'WY', label: 'Wyoming', region: 'West' },
] as const;

export type StateValue = typeof STATES[number]['value'];
